system:
  ip : ""
  port : 8081
  env : "dev"
  version : 1.0.1
mysql:
  host: 127.0.0.1
  port: 3307
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: gvd_db
  username: root
  password: 123456
  logLevel: info
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  poolSize: 100
jwt:
  expires: 8 #过期时间，单位小时
  issuer: "zengxixi"
  secret: "Js*k$pNh"
